services:
  app:
    image: todo-front
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend-prod

  server:
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo-backend-prod
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin
      - REDIS_URL=redis://redis:6379
      - PORT=3001

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis:7
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data

  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    container_name: reverse-proxy-prod
    depends_on:
      - app
      - server

volumes:
  mongo_data:
  redis_data: