services:
  app:
    image: hello-front-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 5173:5173
    container_name: hello-front-dev

  server:
    image: hello-back-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/the_database
    container_name: hello-back-dev

  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis